package org.example.app.core.skills

import java.util.ArrayDeque

/**
 * Authoritative mutable skill state for a player.
 *
 * Persistent restoration uses [setExperience] directly and therefore does not
 * generate gameplay events.
 *
 * Gameplay XP additions use [addExperience], which records the resulting
 * [SkillChange]. The skills feature drains those changes once per game cycle
 * and owns all client synchronization / level-up presentation.
 */
class PlayerSkills {

    private val currentLevels =
        IntArray(Skill.entries.size) { index ->
            Skill.entries[index].defaultLevel
        }

    private val baseLevels =
        IntArray(Skill.entries.size) { index ->
            Skill.entries[index].defaultLevel
        }

    private val experience =
        IntArray(Skill.entries.size) { index ->
            SkillExperience.forLevel(
                Skill.entries[index].defaultLevel,
            )
        }

    /**
     * Changes generated by live gameplay since the last skills sync.
     *
     * This lets any gameplay feature award XP without needing to depend on
     * SkillsFeature or duplicate UpdateStat packet logic.
     */
    private val pendingChanges =
        ArrayDeque<SkillChange>()

    fun currentLevel(
        skill: Skill,
    ): Int =
        currentLevels[skill.id]

    fun baseLevel(
        skill: Skill,
    ): Int =
        baseLevels[skill.id]

    fun experience(
        skill: Skill,
    ): Int =
        experience[skill.id]

    /**
     * Adds live gameplay experience and records the resulting change for the
     * central skills feature to process.
     */
    fun addExperience(
        skill: Skill,
        amount: Int,
    ): SkillChange {
        require(amount >= 0) {
            "Experience amount cannot be negative."
        }

        val change =
            setExperience(
                skill = skill,
                experience =
                    experience(skill) +
                        amount,
            )

        if (change.gainedExperience > 0) {
            pendingChanges.addLast(
                change
            )
        }

        return change
    }

    /**
     * Sets absolute experience without generating a gameplay event.
     *
     * Persistence restoration intentionally uses this method so loading a
     * saved character cannot generate fake level-up notifications.
     */
    fun setExperience(
        skill: Skill,
        experience: Int,
    ): SkillChange {
        val previousExperience =
            this.experience(skill)

        val previousBaseLevel =
            baseLevel(skill)

        val previousCurrentLevel =
            currentLevel(skill)

        val cappedExperience =
            experience.coerceIn(
                minimumValue = 0,
                maximumValue =
                    SkillExperience.MAX_EXPERIENCE,
            )

        val newBaseLevel =
            SkillExperience
                .levelForExperience(
                    cappedExperience
                )

        this.experience[skill.id] =
            cappedExperience

        baseLevels[skill.id] =
            newBaseLevel

        /*
         * If the skill was not boosted/drained, keep current level aligned
         * with the newly-derived base level.
         */
        if (
            previousCurrentLevel ==
            previousBaseLevel
        ) {
            currentLevels[skill.id] =
                newBaseLevel
        }

        return SkillChange(
            skill = skill,
            previousExperience =
                previousExperience,
            experience =
                cappedExperience,
            previousLevel =
                previousBaseLevel,
            level =
                newBaseLevel,
        )
    }

    /**
     * Returns and clears all live gameplay changes generated since the last
     * synchronization pass.
     */
    internal fun drainPendingChanges():
        List<SkillChange> {
        if (pendingChanges.isEmpty()) {
            return emptyList()
        }

        return buildList(
            pendingChanges.size
        ) {
            while (
                pendingChanges.isNotEmpty()
            ) {
                add(
                    pendingChanges.removeFirst()
                )
            }
        }
    }
}