package org.example.app.features.skills

import net.rsprot.protocol.game.outgoing.misc.player.UpdateStatV2
import org.example.app.core.player.Player
import org.example.app.core.skills.Skill
import org.example.app.core.skills.SkillChange
import org.example.app.features.skills.levelup.SkillLevelUpService

/**
 * Owns protocol synchronization and presentation for generic player skills.
 *
 * Gameplay systems mutate Player.skills. This service consumes the resulting
 * pending changes during the normal game-cycle synchronization pass.
 */
internal class SkillService(
    private val levelUpService:
        SkillLevelUpService,
) {

    fun syncInitial(
        player: Player,
    ) {
        val state =
            player.skillSyncState

        if (state.initialSyncSent) {
            return
        }

        for (skill in Skill.entries) {
            sync(
                player = player,
                skill = skill,
            )
        }

        state.initialSyncSent =
            true

        println(
            "[Skills] Synchronized ${Skill.entries.size} skills " +
                "for '${player.username}'."
        )
    }

    /**
     * Public gameplay-facing XP entry point used by commands.
     *
     * The resulting client synchronization occurs in [processPendingChanges].
     */
    fun addExperience(
        player: Player,
        skill: Skill,
        amount: Int,
    ): SkillChange =
        player.skills.addExperience(
            skill = skill,
            amount = amount,
        )

    /**
     * Synchronizes all skill changes generated by gameplay during this cycle.
     */
    fun processPendingChanges(
        player: Player,
    ) {
        val changes =
            player.skills
                .drainPendingChanges()

        for (change in changes) {
            sync(
                player = player,
                skill = change.skill,
            )

            levelUpService.show(
                player = player,
                change = change,
            )
        }
    }

    private fun sync(
        player: Player,
        skill: Skill,
    ) {
        player.session.queue(
            UpdateStatV2(
                skill.id,
                player.skills
                    .currentLevel(skill),
                player.skills
                    .baseLevel(skill),
                player.skills
                    .experience(skill),
            )
        )
    }
}